openapi: '3.0.2'
info:
  title: LndHubX  
  version: '1.0'
servers:
  - url: https://lndhubx.kollider.xyz/api/
paths:
  /nodeinfo:
    get:
      summary: Info about Lndhubx.
      responses:
        '200':
          description: OK
  /create:
    post:
      summary: Creates a new user.
      requestBody:
        description: This creates a new unique user on LndhubX.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CreateUser'
      responses:
        '200':
          description: OK
  /auth:
    post:
      summary: Logs in a new user.
      requestBody:
        description: This will log a user and in an return the JWT tokens.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CreateUser'
      responses:
        '200':
          description: OK
  /balance:
    get:
      summary: Get user balance.
      responses:
        '200':
          description: OK
  /addinvoice:
    get:
      summary: Creates a new invoice.
      parameters:
        - in: query
          name: amount
          schema:
            type: integer
          required: true
          description: The amount of sats the invoice is generated for.
        - in: query
          name: meta 
          schema:
            type: string 
          required: false
          description: Some optional meta data to include in the invoice.
        - in: query
          name: account_id
          schema:
            type: string 
          required: false
          description: If you want to generate the invoice for a specific account otherwise your default account is used.
      responses:
        '200':
          description: OK
  /payinvoice:
    post:
      summary: Pay an invoice.
      requestBody:
        description: This will pay an invoice. Internal payments are possible but no self payments.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/PayInvoice'
      responses:
        '200':
          description: OK
  /getuserinvoices:
    get:
      summary: Gets all invoices that were generated by user.
      responses:
        '200':
          description: OK
  /getavailablecurrencies:
    get:
      summary: Shows you all available currencies to swap into.
      responses:
        '200':
          description: OK
  /swap:
    post:
      summary: Swap one currency for another.
      requestBody:
        description: This will swap any two currencies with each other.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Swap'
      responses:
        '200':
          description: OK
  /quote:
    get:
      summary: Get a quote for a currency swap.
      parameters:
        - in: query
          name: from_currency
          schema:
            type: string 
          required: true
          description: The currency you want to sell.
        - in: query
          name: to_currency
          schema:
            type: string 
          required: true
          description: The currency you want to buy.
        - in: query
          name: amount
          schema:
            type: integer
          required: true
          description: The amount you want to swap. Note BTC is denominated in BTC not Sats.
      responses:
        '200':
          description: OK
  /gettxs:
    get:
      summary: Gets all transactions made by user.
      description: This includes deposits, withdrawals and swaps.
      responses:
        '200':
          description: OK


components:
  requestBodies:
    CreateUser:
      type: object
      properties:
        username:
          type: string
          description: A unique username.
        password:
          type: string
          description: A unique strong password.
    PayInvoice:
      type: object
      properties:
        payment_request:
          type: string
          description: The LN payment request to be paid.
    Swap:
      type: object
      properties:
        from_currency:
          type: string
          description: The currency you want to sell.
        to_currency:
          type: string
          description: The currency you wan to buy.
        amount:
          type: string
          description: The amount you want to swap.
  