version: "3.9"
services:
  db:
    network_mode: "host"
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: konstantin
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: pg_isready -U postgres
    ports:
    - "5432:5432"
  api:
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: api.Dockerfile
    image: kolliderhq/lndhubx-api:v1.0.0
    environment:
      SECRET_KEY: "redacted"
    ports:
    - "8080:8080"
  bank:
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: bank.Dockerfile
    image: kolliderhq/lndhubx-bank:v1.0.0
    volumes:
      - ${PWD}/config:/config
    environment:
      RUST_BACKTRACE: full
  dealer:
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: dealer.Dockerfile
    image: kolliderhq/lndhubx-dealer:v1.0.0
