### API Config
psql_url = "<psql-url>"

api_zmq_push_address = "tcp://127.0.0.1:5555"
api_zmq_subscribe_address = "tcp://127.0.0.1:5556"

### Bank Config
zmq_pull_address = "tcp://127.0.0.1:5555"
zmq_publish_address = "tcp://127.0.0.1:5556"

dealer_pull_address = "tcp://127.0.0.1:5557"
dealer_push_address = "tcp://127.0.0.1:5558"

tls_path = "path/to/tls/cert"
macaroon_path = "path/to/admin/macaroon"
node_url = "<lnd-node-url>"

### Dealer Conifg
bank_push_address = "tcp://127.0.0.1:5557"
bank_pull_address = "tcp://127.0.0.1:5558"

kollider_ws_url = "<kollider-ws-url>"
kollider_api_key = "<kollider-api-key>"
kollider_api_secret = "<kollider-api-secret>"
kollider_api_passphrase = "<kollider-api-passphrase>"